version: "3.1"

services:
  db:
    image: mysql
    container_name: mysql-engine
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_starter
    ports:
      - 3306:3306
    volumes:
      - datavolume:/var/lib/mysql

volumes:
  datavolume:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 3306:3306
